# This file was generated by GoReleaser. DO NOT EDIT.
cask "gwam" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "d671b2588318aaae06e9bcd58d97d24967367cc0f3d327dec8ba7d3b22d4d356"
      url "https://github.com/GarrettCannon/gwam/releases/download/v#{version}/gwam_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/garrettcannon/gwam"
    end
    on_arm do
      sha256 "2ce73569d4d8f7dad3a3f29f716b1aea562957ba82ea8f74a6782e7cdf3826aa"
      url "https://github.com/GarrettCannon/gwam/releases/download/v#{version}/gwam_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/garrettcannon/gwam"
    end
  end

  on_linux do
    on_intel do
      sha256 "2c2b865dc2793caee91413a5aaaaf514474143b4dc1bd508d6935aebe2d98edc"
      url "https://github.com/GarrettCannon/gwam/releases/download/v#{version}/gwam_#{version}_linux_amd64.tar.gz",
        verified: "github.com/garrettcannon/gwam"
    end
    on_arm do
      sha256 "ba66caf4d82e08b3f4ba393fc12342aba0809d50d2c8cb22c27cb246417a966f"
      url "https://github.com/GarrettCannon/gwam/releases/download/v#{version}/gwam_#{version}_linux_arm64.tar.gz",
        verified: "github.com/garrettcannon/gwam"
    end
  end

  name "gwam"
  desc "A tmux-style terminal multiplexer"
  homepage "https://github.com/garrettcannon/gwam"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gwam"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gwam"]
    end
  end

  # No zap stanza required

end
