# This file was generated by GoReleaser. DO NOT EDIT.
cask "gwam" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "913e139ed845db8dd58a33c3f42b394bda5ce05a7c40894146826df80ef03476"
      url "https://github.com/GarrettCannon/gwam/releases/download/v#{version}/gwam_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/garrettcannon/gwam"
    end
    on_arm do
      sha256 "f1a944745936ab53636306183aaa33ff28db8068afb5ffa7348a0754c6393128"
      url "https://github.com/GarrettCannon/gwam/releases/download/v#{version}/gwam_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/garrettcannon/gwam"
    end
  end

  on_linux do
    on_intel do
      sha256 "7ac395032aed3df76bc051b53207bc1430fd35d454161948b2d8f33efffda7aa"
      url "https://github.com/GarrettCannon/gwam/releases/download/v#{version}/gwam_#{version}_linux_amd64.tar.gz",
        verified: "github.com/garrettcannon/gwam"
    end
    on_arm do
      sha256 "355cf2611955617bbcb4f5acb8749e94596830c2af914ba4a755b0db80588041"
      url "https://github.com/GarrettCannon/gwam/releases/download/v#{version}/gwam_#{version}_linux_arm64.tar.gz",
        verified: "github.com/garrettcannon/gwam"
    end
  end

  name "gwam"
  desc "A tmux-style terminal multiplexer"
  homepage "https://github.com/garrettcannon/gwam"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gwam"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gwam"]
    end
  end

  # No zap stanza required

end
