# This file was generated by GoReleaser. DO NOT EDIT.
cask "gwam" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "3bc2bb861f141938c6c2f4fef551300811760040ab4203d664fcd764103cf10e"
      url "https://github.com/GarrettCannon/gwam/releases/download/v#{version}/gwam_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/garrettcannon/gwam"
    end
    on_arm do
      sha256 "925e7636968835a727c7b7c21938ef8afc9f54300fb86f11911b3e0c293ed99d"
      url "https://github.com/GarrettCannon/gwam/releases/download/v#{version}/gwam_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/garrettcannon/gwam"
    end
  end

  on_linux do
    on_intel do
      sha256 "3c410578436388632ce4e5440fa1cdae6fcba5be516760a7a2e9894d3b414691"
      url "https://github.com/GarrettCannon/gwam/releases/download/v#{version}/gwam_#{version}_linux_amd64.tar.gz",
        verified: "github.com/garrettcannon/gwam"
    end
    on_arm do
      sha256 "8ea072a5e042c4006f75810e2e51e7ada69854a1f50c4df7eda4e09ce9fae847"
      url "https://github.com/GarrettCannon/gwam/releases/download/v#{version}/gwam_#{version}_linux_arm64.tar.gz",
        verified: "github.com/garrettcannon/gwam"
    end
  end

  name "gwam"
  desc "A tmux-style terminal multiplexer"
  homepage "https://github.com/garrettcannon/gwam"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gwam"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gwam"]
    end
  end

  # No zap stanza required

end
