# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnil" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "507c31ca78342be759a3f74b03f38db5ce932a32387739e958ef895cd13679e6"
      url "https://github.com/GarrettCannon/mnil/releases/download/v#{version}/mnil_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/garrettcannon/mnil"
    end
    on_arm do
      sha256 "d4c96698ee63c3e7182bf26c9a6d058144c88e5b258ada541408f9bb199abc9b"
      url "https://github.com/GarrettCannon/mnil/releases/download/v#{version}/mnil_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/garrettcannon/mnil"
    end
  end

  on_linux do
    on_intel do
      sha256 "fa487e100313adbc9edc68308ea2979dcad49a42e4e9b16100d499fa6aaa55ac"
      url "https://github.com/GarrettCannon/mnil/releases/download/v#{version}/mnil_#{version}_linux_amd64.tar.gz",
        verified: "github.com/garrettcannon/mnil"
    end
    on_arm do
      sha256 "2d9296f48dea8e2174316c7fc66e6cadf27c03d53de7421ec04190e4793ca159"
      url "https://github.com/GarrettCannon/mnil/releases/download/v#{version}/mnil_#{version}_linux_arm64.tar.gz",
        verified: "github.com/garrettcannon/mnil"
    end
  end

  name "mnil"
  desc "TUI log viewer that tails piped or spawned commands"
  homepage "https://github.com/garrettcannon/mnil"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mnil"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mnil"]
    end
  end

  # No zap stanza required

end
