# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnil" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "5d99f40ce11651940bf817485b422e644d7636f398fd019bff84096acf38b997"
      url "https://github.com/GarrettCannon/mnil/releases/download/v#{version}/mnil_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/garrettcannon/mnil"
    end
    on_arm do
      sha256 "3e0e8e246f86393fd15cdab257b757ffb32e3869133f8ddf46ee81316fa626c3"
      url "https://github.com/GarrettCannon/mnil/releases/download/v#{version}/mnil_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/garrettcannon/mnil"
    end
  end

  on_linux do
    on_intel do
      sha256 "0a0b58e1d80023b8526a4106ffe28f196cbb01aac99a5b3717b248dbf66f97e8"
      url "https://github.com/GarrettCannon/mnil/releases/download/v#{version}/mnil_#{version}_linux_amd64.tar.gz",
        verified: "github.com/garrettcannon/mnil"
    end
    on_arm do
      sha256 "ea7f82de43008551df6377285aec7753899b5ebf56f0008702af157b942932af"
      url "https://github.com/GarrettCannon/mnil/releases/download/v#{version}/mnil_#{version}_linux_arm64.tar.gz",
        verified: "github.com/garrettcannon/mnil"
    end
  end

  name "mnil"
  desc "TUI log viewer that tails piped or spawned commands"
  homepage "https://github.com/garrettcannon/mnil"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mnil"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mnil"]
    end
  end

  # No zap stanza required

end
