# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnil" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "7e5e0148eb7e49a49c95700bdf3eff4c6c162cdea555c60a56e1ab39ce4fd261"
      url "https://github.com/GarrettCannon/mnil/releases/download/v#{version}/mnil_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/garrettcannon/mnil"
    end
    on_arm do
      sha256 "585f7b3f91965e613164b64385df5c485b6e067f91953d50858a07d353072d68"
      url "https://github.com/GarrettCannon/mnil/releases/download/v#{version}/mnil_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/garrettcannon/mnil"
    end
  end

  on_linux do
    on_intel do
      sha256 "517c2d66cdfaf65c18aacc4cb5bc4792add1d94d948d4112c85f949846079c95"
      url "https://github.com/GarrettCannon/mnil/releases/download/v#{version}/mnil_#{version}_linux_amd64.tar.gz",
        verified: "github.com/garrettcannon/mnil"
    end
    on_arm do
      sha256 "19ffa5b1560598c35e80aeda61b7a495e25a92ced17fb6195760c4498794e526"
      url "https://github.com/GarrettCannon/mnil/releases/download/v#{version}/mnil_#{version}_linux_arm64.tar.gz",
        verified: "github.com/garrettcannon/mnil"
    end
  end

  name "mnil"
  desc "TUI log viewer that tails piped or spawned commands"
  homepage "https://github.com/garrettcannon/mnil"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mnil"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mnil"]
    end
  end

  # No zap stanza required

end
